# docker-compose.yml

version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM={ALGORITHM}
      - MY_GMAIL_SECRET_KEY_CONTACT={MY_GMAIL_SECRET_KEY_CONTACT}
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: gaye
      POSTGRES_PASSWORD: Postgres.2424
      POSTGRES_DB: fastapi_app_db
    ports:
      - "5433:5433"


