# docker-compose.yml

version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://gaye:Postgres.2424@localhost:5433/fastapi_app_db
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM={ALGORITHM}
      - MY_GMAIL_SECRET_KEY_CONTACT={MY_GMAIL_SECRET_KEY_CONTACT}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5433"




